workflows:
  build_app:
    name: Build PCB Inspector
    max_build_duration: 60
    environment:
      flutter: stable

    scripts:
      - name: Create Flutter project
        script: |
          flutter create pcb_inspector_project
          rm -rf pcb_inspector_project/lib/*
          cp -r lib pcb_inspector_project/

      - name: Build APK
        script: |
          cd pcb_inspector_project
          flutter build apk --release

    artifacts:
      - pcb_inspector_project/build/app/outputs/flutter-apk/app-release.apk

    publishing:
      email:
        recipients:
          - "allu.shark@gmail.com"
        notify:
          success: true
          failure: true
